name: EC2 Self-Hosted Test

on:
  push:
    branches: [ "main" ] # Убедитесь, что ваша ветка называется main, а не master

jobs:
  check-ec2:
    runs-on: [self-hosted, ec2] # Ваши метки раннера

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: System Info
        run: |
          echo "Билд запущен успешно!"
          whoami
          uptime
          docker --version
