name: Deploy Application

on:
  push:
    branches: [ "main" ] # Срабатывает при пуше в main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, ec2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          # Собираем образ (замените my-app на название вашего проекта)
          docker build -t my-app:latest .

      - name: Stop Old Container
        run: |
          # Останавливаем старый контейнер, если он запущен, чтобы освободить порт
          docker stop my-app-container || true
          docker rm my-app-container || true

      - name: Run New Container
        run: |
          # Запускаем новый контейнер (например, на порту 80)
          docker run -d --name my-app-container -p 8081:80 my-app:latest
